yes | cp -rf ~/Konphig/.bash_aliases ~ >/dev/null 2>&1
yes | cp -rf ~/Konphig/.bash_variables ~ >/dev/null 2>&1
yes | cp -rf ~/Konphig/.bash_functions ~ >/dev/null 2>&1
yes | cp -rf ~/Konphig/.bash_profile ~ >/dev/null 2>&1
yes | cp -rf ~/Konphig/.bashrc ~ >/dev/null 2>&1
yes | cp -rf ~/Konphig/.git-prompt.sh ~ >/dev/null 2>&1
yes | cp -rf ~/Konphig/.gitconfig ~ >/dev/null 2>&1
yes | cp -rf ~/Konphig/.profile ~ >/dev/null 2>&1
yes | cp -rf ~/Konphig/.tmux.conf ~ >/dev/null 2>&1
yes | cp -rf ~/Konphig/.vimrc ~ >/dev/null 2>&1