#!/bin/bash

# get the current git branch
function gb {

	# help and usage
	if [[ "$1" == "-h" || "$1" == "--help" ]] ; then
		echo -e "\033[93mgb ~ get the current git branch\033[0m"
		echo
		echo "gb [-h]"
		echo "  -h, --help    show this menu and exit"
		return 0
	fi

	if ! git status > /dev/null 2>&1 ; then
		>&2 echo "gitb: err: not a git repository"
		return 1
	fi

	# shellcheck disable=SC2063
	git branch | grep \* | cut -d ' ' -f2
}
