#!/bin/bash

# add an alias on the fly
function adda {
	# help and usage
	if [[ "$1" == "-h" || "$1" == "--help" ]] ; then
		echo -e "\033[93madda [-h] ALIAS MEANING\033[0m"
		echo "Add an alias on the fly"
		echo "  alias      the new alias"
		echo "  meaning    the full command that the alias expands to"
		return 0
	fi

	if [[ $# -ne 2 ]] ; then
		echo "adda: err: incorrect number of arguments"
		return 1
	fi

	local file
	if [[ ! -f ~/.bash_aliases ]] ; then
		file=~/.bashrc
	else
		file=~/.bash_aliases
	fi

	echo "alias $1='$2'" >> "$file"
	source ~/.bashrc
}
