#!/bin/bash

# add a variable on the fly
function addv {
	# help and usage
	if [[ "$1" == "-h" || "$1" == "--help" ]] ; then
		echo -e "\033[93maddv [-h] NAME VALUE\033[0m"
		echo "Add an variable on the fly"
		echo "  name     the name of the new variable"
		echo "  value    the value of the new variable"
		return 0
	fi

	if [[ $# -ne 2 ]] ; then
		echo "addv: err: incorrect number of arguments"
		return 1
	fi

	local file
	if [[ ! -f ~/.bash_variables ]] ; then
		file=~/.bashrc
	else
		file=~/.bash_variables
	fi

	echo "export $1=$2" >> "$file"
	source ~/.bashrc
}
