#!/bin/bash

# change to a different prompt (different PS1 variables)
function dp {

    local red green reset

	if [[ $# -eq 0 ]] ; then
		# default
		export __PS1__=''
    elif [[ "$1" == "-h" || "$1" == "--help" ]] ; then
        # help menu
        echo -e "\033[93mdp ~ change to a different prompt\033[0m"
        echo
        echo "dp [-h] [NUM]"
        echo "  [num]    the prompt index"
        echo
        echo "Available prompts:"
        echo "  default: full prompt with face"
        echo "  1: minimalist"
        echo "  2: date only"
        echo "  3: date and pwd"
        echo "  4: mood based on last command"
        echo "  5: date and git prompt"
        echo "  6: comment box"
	elif [[ "$1" == "1" ]] ; then
		# minimalist
		export __PS1__="\\$ "
	elif [[ "$1" == "2" ]] ; then
		# just date
		export __PS1__="[\A] > "
	elif [[ "$1" == "3" ]] ; then
		# full date and pwd
		export __PS1__="[\u@\h] \d, \T <\W> \\$ "
	elif [[ "$1" == "4" ]] ; then
		# mood based on last command
		export __PS1__="\`if [ \$? = 0 ]; then echo \[\e[33m\]^_^\[\e[0m\]; else echo \[\e[31m\]O_O\[\e[0m\]; fi\` \\$ "
    elif [[ "$1" == "5" ]] ; then
        # nice git prompt
        red='\[\033[0;31m\]'
        green='\[\033[0;32m\]'
        reset='\[\033[0m\]'
        # shellcheck disable=SC2046
        if test $(git status 2> /dev/null | grep -c :) -eq 0 ; then
            git_color="${green}"
        else
            git_color="${red}"
        fi
        # shellcheck disable=SC2155
        export __PS1__="${reset}[\A] \W${git_color}$(__git_ps1) ${reset}> "
    elif [[ "$1" == "6" ]] ; then
        export __PS1__=":; "
	else
		>&2 echo "dp: err: invalid prompt index, must be [1,6]"
		return 1
	fi
}
