#!/bin/bash

# extract compressed and zipped files automatically
function extract {

	# help and usage
	if [[ "$1" == "-h" || "$1" == "--help" ]] ; then
		echo -e "\033[93mextract ~ extract compressed and zipped files automatically\033[0m"
		echo
		echo "extract [-h] FILE..."
		echo "  -h, --help    show this menu and exit"
		echo "  file          (+) the file(s) to extract"
		return 0
	fi

	local file code
	code=0
	for file in "$@" ; do
		if [[ -f "$file" ]] ; then
			case "$1" in
				*.tar.bz2)      tar xjf "$file" ;;
				*.tar.gz)       tar xzf "$file" ;;
				*.bz2)          bunzip2 "$file" ;;
				*.rar)          unrar x "$file" ;;
				*.gz)           gunzip "$file" ;;
				*.tar)          tar xf "$file" ;;
				*.xz)           tar xJf "$file" ;;
				*.tbz2)         tar xjf "$file" ;;
				*.tgz)          tar xzf "$file" ;;
				*.zip)          unzip "$file" ;;
				*.Z)            uncompress "$file" ;;
				*)              echo "extract: err: '$file' cannot be extracted via extract" ; code=1 ;;
			esac
		else
			>&2 echo "extract: err: '$file' is not a valid file"
			code=1
		fi
	done

	exit $code
}
