#!/bin/bash

# select files at random from a directory
function get {

	# help and usage
	if [[ "$1" == "-h" || "$1" == "--help" ]] ; then
		echo -e "\033[93mget ~ select files at random from a directory\033[0m"
		echo
		echo "get [-h] [NUM]"
		echo "  -h, --help    show this menu and exit"
		echo "  num           the number of random files to get (default: 1)"
		return 0
	fi

	[ -n "$1" ] && [ "$1" -eq "$1" ] 2>/dev/null
	# shellcheck disable=SC2181
	if [[ $? -ne 0 ]] ; then
		>&2 echo "get: err: argument must be a number"
		return 1
	elif [[ $1 -lt 1 ]] ; then
		>&2 echo "get: err: argument must be a positive integer"
		return 1
	fi

	local files
	files=( * )

	# shellcheck disable=SC2086
	for _ in $(seq 1 ${1:-1}) ; do
		echo "${files[$RANDOM % ${#files[@]} ]}"
	done
}
