#!/bin/bash

# get location for your public IP address
function getlocation {

	# help and usage
	if [[ "$1" == "-h" || "$1" == "--help" ]] ; then
		echo -e "\033[93mgetlocation ~ get location for your public IP address\033[0m"
		echo
		echo "getlocation [-h] FILETYPE"
		echo "  -h, --help    show this menu and exit"
		return 0
	fi

	local myip details frmt index line city country state location

	myip=$(dig +short myip.opendns.com @resolver1.opendns.com)
	details=$(lynx -dump "$(publicip)".ip-adress.com | egrep 'City|State Code|Country Code')
	frmt="IP: $myip\n"
	index=0

	while IFS= read -r line ; do
		if [[ $index -eq 0 ]] ; then
			city=$(echo $line | cut -d " " -f2-)
			let index=index+1
		elif [[ $index -eq 1 ]] ; then
			country=$(echo $line | cut -d " " -f3-)
			let index=index+1
		else
			state=$(echo $line | cut -d " " -f3-)
			let index=index+1
		fi
	done <<< "$details"

	location="Location: $city, $state, $country"
	frmt+="$location"
	echo -e $frmt
}
