#!/bin/bash

# kill process by name
function kp {

	# help and usage
	if [[ "$1" == "-h" || "$1" == "--help" ]] ; then
		echo -e "\033[93mkp ~ kill process by name\033[0m"
		echo
		echo "kp [-h] FILETYPE"
		echo "  -h, --help    show this menu and exit"
		return 0
	fi

	if [[ $# -ne 1 ]] ; then
		>&2 echo "kp: err: incorrect number of arguments"
		return 1
	fi

	local pid

	ps aux | grep "$1" > /dev/null
	pid=$(pgrep "$1")
	if [[ "$pid" != "" ]] ; then
		kill -9 "$pid"
		if [[ "$?" == "0" ]] ; then
			echo "PID $pid ($1) killed"
		fi
	else
		>&2 echo "kp: err: no processes killed, could not find PID for process '$1'"
		return 1
	fi
}
