#!/bin/bash

# show percentage of each filetype in the current directory
function per {

	# help and usage
	if [[ "$1" == "-h" || "$1" == "--help" ]] ; then
		echo -e "\033[93mper ~ show percentage of each filetype in the current directory\033[0m"
		echo
		echo "per [-h]"
		echo "  -h, --help    show this menu and exit"
		return 0
	fi

	local total file ext vars v output

	total=0
	vars=()
	for file in * ; do
		if [[ ! -f "$file" ]] ; then continue ; fi

		if [[ "$file" == *.* ]] ; then
			ext="${file##*.}"
		else
			ext=
		fi

		if ! [[ "$ext" =~ ^[a-zA-Z]+[a-zA-Z0-9]*$ ]] ; then continue ; fi

		if [[ "$ext" == "" ]] ; then
			if [[ -n "$extensionless" ]] ; then
				(( extensionless += 1 ))
			else
				local extensionless
				extensionless=1
				vars+=( extensionless )
			fi
		else
			if [[ -n "${!ext}" ]] ; then
				(( "${ext}" += 1 ))
			else
				local "${ext}"
				# shellcheck disable=SC2229,SC2162
				read "${ext}" <<< 1
				vars+=( "${ext}" )
			fi
		fi

		(( total += 1 ))
	done

	if [[ $total -eq 0 ]] ; then
		echo "No files here"
		return 0
	fi

	output=
	for v in "${vars[@]}" ; do
		# shellcheck disable=SC2001
		output="${output}$(printf '%s' "$(sed 's/extensionless/_/g' <<< "${v}: ")")"
		output="${output}$(printf '%s' "${!v} (")"
		output="${output}$(printf '%.2f' "$(bc <<< "scale=10; (${!v}/$total) * 100")")"
		output="${output}$(printf '%s' '%)\n')"
	done

	echo -e "$output" | column -t
}
