#!/bin/bash

# snag recently downloaded files to the current directory
function snag {

	# help and usage
	if [[ "$1" == "-h" || "$1" == "--help" ]] ; then
		echo -e "\033[93msnag ~ snag most recently downloaded files to the current directory\033[0m"
		echo
		echo "snag [-h] [NUM]"
		echo "  -h, --help    show this menu and exit"
		echo "  num           the number of files to snag (default: 1)"
		return 0
	fi

	local num file
	if [[ $# -eq 0 ]] ; then
		num=1
	else
		num=$1
	fi

	[ -n "$num" ] && [ "$num" -eq "$num" ] 2>/dev/null
	# shellcheck disable=SC2181
	if [[ $? -ne 0 ]] ; then
		echo "snag: err: argument must be a number"
		return 1
	fi
	if [[ "$num" -lt 1 ]] ; then
		echo "snag: err: argument must be a positive integer"
		return 1
	fi

	if [[ ! -d ~/Downloads ]] ; then
		echo "snag: err: no such directory ~/Downloads"
		return 1
	fi

	for _ in $(seq 1 "$num") ; do
		# shellcheck disable=SC2012
		file=$(ls -t ~/Downloads | head -1)
		mv ~/Downloads/"$file" .
	done
}
